### ISSUE TITLE
Redis cache not work with file upload

### ISSUE THREAD

**Issue by maxwkfcc** [duncanmcclean/guest-entries#28]
### Bug Description

I am using the Guest Entires to do a front end submission of form.  However, when the submission is done, the picture uploaded are not showing in the collection entry.  After some troubleshoot, it seems to be the Redis cache is not refreshing the Gallery. 

~~If I am using file cache, this is not happening.~~
If I dont use a cache, this is not happening.

### Steps to reproduce

1. Configure the system with Redis cache
2. Create a form with file upload to a collection entries
3. Submit the form with file upload
4. Go to Control Panel and take a look at the uploaded file, the are not exists
5. Then I go to the Utilities and clear the Cache
6. Go back to the entry in Control Panel, then can see the uploaded file again

### Environment

Licensing
SITE
No site license key
CORE
 Statamic Pro	3.3.34	Unlicensed
ADDONS
 Guest Entries	1.2.1	Unlicensed
 Live Search	1.5.1	
 Livewire	2.9.0	
 Oreos	1.2.0	
UNLISTED ADDONS
 Guest Entries Support	dev-main
 Eloquent Driver	0.3.0

**Comment by duncanmcclean** [comment]
Possibly related to duncanmcclean/duplicator#49

**Comment by duncanmcclean** [comment]
Sorry, I've just tried to reproduce this but wasn't able to.

I changed the cache driver in my `.env` like so: `CACHE_DRIVER=redis`

After that, I submitted the guest entries form with a file upload. I can see the file has persisted fine in the Control Panel when looking at Assets.

Are you able to reproduce in a fresh site that you'd be able to share?

**Comment by maxwkfcc** [comment]
Just to write a note here.  I wrote in the previous message if I am using file cache, it is not happening.  I made a mistake.  Should be it is not happening if I do not put cache on.

**Comment by maxwkfcc** [comment]
> Sorry, I've just tried to reproduce this but wasn't able to.
> 
> I changed the cache driver in my `.env` like so: `CACHE_DRIVER=redis`
> 
> After that, I submitted the guest entries form with a file upload. I can see the file has persisted fine in the Control Panel when looking at Assets.
> 
> Are you able to reproduce in a fresh site that you'd be able to share?

I will see what I can do.

**Comment by maxwkfcc** [comment]
Hi Duncan,

I have sent you a private message in discord on a screen recording.  See if that helps.

**Comment by duncanmcclean** [comment]
> Just to write a note here. I wrote in the previous message if I am using file cache, it is not happening. I made a mistake. Should be it is not happening if I do not put cache on.

What do you mean by 'not putting cache on'? Which cache are you referring to?

**Comment by maxwkfcc** [comment]
> > Just to write a note here. I wrote in the previous message if I am using file cache, it is not happening. I made a mistake. Should be it is not happening if I do not put cache on.
> 
> What do you mean by 'not putting cache on'? Which cache are you referring to?

Hi Duncan,

I have made the following config to test.


Success
=========
STATAMIC_STATIC_CACHING_STRATEGY=null
CACHE_DRIVER=none

Fail - Need to clear application cache
=========
STATAMIC_STATIC_CACHING_STRATEGY=null
CACHE_DRIVER=file

STATAMIC_STATIC_CACHING_STRATEGY=null
CACHE_DRIVER=redis

STATAMIC_STATIC_CACHING_STRATEGY=full
CACHE_DRIVER=redis

**Comment by duncanmcclean** [comment]
Sorry, I'm still not able to reproduce using the `file` or `redis` drivers. And without being able to reproduce, I can't fix the issue.

Could you provide a repository of a site where you're having this issue (I don't mind if it's a test site)?

_Note: Static caching won't make any difference to the asset showing up/not showing up - it only has to do with front-end caching._

**Comment by maxwkfcc** [comment]
> Sorry, I'm still not able to reproduce using the `file` or `redis` drivers. And without being able to reproduce, I can't fix the issue.
> 
> Could you provide a repository of a site where you're having this issue (I don't mind if it's a test site)?
> 
> _Note: Static caching won't make any difference to the asset showing up/not showing up - it only has to do with front-end caching._

Hi Duncan,

Really appreciate for your help.  I will see if I can create a site for the troubleshoot.

Thanks

**Comment by maxwkfcc** [comment]
Hi Duncan,

I have created a site for your test.  Please see discord message.

**Comment by duncanmcclean** [comment]
Thanks for providing details to pull down the site. I was able to reproduce the issue & fix the bug. 

If you update to [v1.2.2](https://github.com/duncanmcclean/guest-entries/releases/tag/v1.2.2), the issue should hopefully be resolved. Please let me know if you're still running into this issue.

**Comment by maxwkfcc** [comment]
> Thanks for providing details to pull down the site. I was able to reproduce the issue & fix the bug.
> 
> If you update to [v1.2.2](https://github.com/duncanmcclean/guest-entries/releases/tag/v1.2.2), the issue should hopefully be resolved. Please let me know if you're still running into this issue.

Thanks Duncan.  It works perfectly.  Cheers
