### ISSUE TITLE
Succes key not working

### ISSUE THREAD

**Issue by robdekort** [duncanmcclean/guest-entries#45]
### Description

```antlers
{{ if {session:has key="success"} }}
    <p>You've filled in the thing properly. Good job!</p>
{{ /if }}
```

This code should work but doesn't. 

### Steps to reproduce

1. Add that code
2. Push an entry
3. See nothing

### Environment

Environment
Application Name: Stichting Lutje Geluk
Laravel Version: 10.7.1
PHP Version: 8.2.3
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
URL: lutjegeluk.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: dev-master PRO

Statamic Addons
doublethreedigital/guest-entries: 2.1.1
statamic/eloquent-driver: 1.2.0
studio1902/statamic-peak-browser-appearance: 2.0-beta.2
studio1902/statamic-peak-commands: 2.0-beta.1
studio1902/statamic-peak-seo: 2.0-beta.2
studio1902/statamic-peak-tools: 3.0-beta.2

**Comment by duncanmcclean** [comment]
Turns out I was wrong, it wasn't possible. It is now :)
