### ISSUE TITLE
Date field does not clear when empty

### ISSUE THREAD

**Issue by ewhicher** [duncanmcclean/guest-entries#67]
### Description

I have an entry that has a date field in the blueprint called `due`.

I can set and update that field no problem, but when I try to submit an empty or null date it saves with today's date.

I need this field to be optional.

Thanks!

### Steps to reproduce

Make an entry with a date field.

Include an empty text field in your `update` or `create` form with the handle of the field as the name attr and an empty value.

Save.

### Environment

Environment
Application Name: Statamic
Laravel Version: 10.48.10
PHP Version: 8.2.11
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: cmmt.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.57.2 Solo

Statamic Addons
duncanmcclean/guest-entries: 3.2.0

**Comment by duncanmcclean** [comment]
Should be fixed in [v4.0.1](https://github.com/duncanmcclean/guest-entries/releases/tag/v4.0.1).
